import {
  armPendingActivityRating,
  clearPendingActivityRating,
  ensureReviewItems,
  getPendingActivityRating,
  listActivityCounts,
  listActivityReviewState,
  listDue,
  listLocks,
  listSchedule,
  markActivityDifficulty,
  previewRatings,
  retentionStats,
  submitRating,
} from "./handlers";

export const review = {
  armPendingActivityRating,
  clearPendingActivityRating,
  ensureReviewItems,
  getPendingActivityRating,
  listActivityCounts,
  listActivityReviewState,
  listDue,
  listLocks,
  listSchedule,
  markActivityDifficulty,
  previewRatings,
  retentionStats,
  submitRating,
};
