import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {
  type ElectronApplication,
  _electron as electron,
  expect,
  type Page,
  test,
} from "@playwright/test";
import { findLatestBuild, parseElectronApp } from "electron-playwright-helpers";
import { freshProfileArg } from "./fresh-profile";

/**
 * Spec: docs/specs/quiz-ai-import.md -- create a Quiz by importing a Markdown
 * file generated by an AI, through the multi-step activity dialog.
 */

let electronApp: ElectronApplication;
let page: Page;
let quizFile: string;

/** Whether the quiz dialog was shaking, each time that changed. */
interface ShakeRecorder {
  shakes: boolean[];
}

/** Where the stubbed shell.openExternal records the URLs it was asked to open. */
interface UrlRecorder {
  openedUrls: string[];
}

const CRLF = /\r\n/g;
const IMPORT_FROM_AI = /Import from an AI/;

const QUIZ_MARKDOWN = `Claro! Aqui está o quiz:

\`\`\`markdown
## Question 1
What is 2 + 2?

- [ ] 3
- [x] 4
- [ ] 5

## Question 2
Capital of France?

- [x] Paris
- [ ] Rome
\`\`\`
`;

test.beforeAll(async () => {
  const latestBuild = findLatestBuild();
  const appInfo = parseElectronApp(latestBuild);
  process.env.CI = "e2e";

  quizFile = path.join(
    fs.mkdtempSync(path.join(os.tmpdir(), "quiz-")),
    "quiz.md"
  );
  fs.writeFileSync(quizFile, QUIZ_MARKDOWN);

  electronApp = await electron.launch({
    args: [appInfo.main, freshProfileArg()],
  });
  page = await electronApp.firstWindow();

  // Record instead of opening a real browser.
  await electronApp.evaluate(({ shell }) => {
    const opened: string[] = [];
    (globalThis as unknown as UrlRecorder).openedUrls = opened;
    shell.openExternal = (url: string) => {
      opened.push(url);
      return Promise.resolve();
    };
  });
});

test.afterAll(async () => {
  // See activities-navigation.test.ts for why app.exit() instead of close().
  await electronApp.evaluate(({ app }) => app.exit());
  fs.rmSync(path.dirname(quizFile), { force: true, recursive: true });
});

async function openImportStep(quizName: string) {
  const uniqueSuffix = Date.now();
  const programName = `E2E Import Program ${uniqueSuffix}`;
  const moduleName = `E2E Import Module ${uniqueSuffix}`;

  // Start from the Programs page, whatever a previous test left open.
  await page.keyboard.press("Escape");
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.getByRole("link", { exact: true, name: "Programs" }).click();
  await page.getByRole("button", { name: "New program" }).click();
  await page.getByLabel("Name").fill(programName);
  await page.getByRole("button", { name: "Save" }).click();
  await page.getByRole("button", { name: new RegExp(programName) }).click();
  await page.getByRole("button", { name: "New module" }).click();
  await page.getByLabel("Name").fill(moduleName);
  await page.getByRole("button", { name: "Save" }).click();
  await page
    .getByRole("row", { name: new RegExp(moduleName) })
    .getByLabel("View activities")
    .click();

  await page.getByRole("button", { name: "New activity" }).click();
  const dialog = page.getByRole("dialog");
  await dialog.getByLabel("Title").fill(quizName);
  await dialog.getByRole("radio", { name: "Quiz" }).click();
  await dialog.getByRole("button", { name: "Next" }).click();

  await expect(dialog.getByText("Step 2 of 3")).toBeVisible();
  await dialog.getByRole("radio", { name: IMPORT_FROM_AI }).click();
  await dialog.getByRole("button", { name: "Next" }).click();

  await expect(dialog.getByText("Step 3 of 3")).toBeVisible();
  return dialog;
}

test("imports an AI-generated Markdown quiz through the multi-step dialog", async () => {
  const quizName = `E2E Imported Quiz ${Date.now()}`;
  const dialog = await openImportStep(quizName);

  await dialog.getByLabel("Theme").fill("Basic math");
  await dialog
    .getByRole("button", { name: "Copy prompt and open ChatGPT" })
    .click();

  await expect
    .poll(() =>
      electronApp.evaluate(
        () => (globalThis as unknown as UrlRecorder).openedUrls.length
      )
    )
    .toBe(1);
  const [openedUrl] = await electronApp.evaluate(
    () => (globalThis as unknown as UrlRecorder).openedUrls
  );
  // The Windows clipboard hands text back with CRLF line breaks.
  const copied = (
    await electronApp.evaluate(({ clipboard }) => clipboard.readText())
  ).replace(CRLF, "\n");
  expect(copied).toContain("Basic math");
  expect(copied).toContain("## Question 1");
  expect(openedUrl).toBe(
    `https://chatgpt.com/?q=${encodeURIComponent(copied)}`
  );

  await dialog
    .getByLabel("Drag the .md file here or click to choose")
    .setInputFiles(quizFile);
  await expect(dialog.getByText("2 questions read")).toBeVisible();
  await dialog.getByRole("button", { name: "Create quiz (2)" }).click();

  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page
    .getByRole("row", { name: new RegExp(quizName) })
    .getByLabel("Take quiz")
    .click();

  const runner = page.getByRole("dialog", { name: quizName });
  await expect(runner.getByText("What is 2 + 2?")).toBeVisible();
});

test("keeps a long imported quiz inside the dialog, with its buttons reachable", async () => {
  // Ten long questions with LaTeX, like a real AI answer: the preview used to
  // widen the dialog past the window (nowrap text) and push its footer out
  // of view (no height limit).
  const longQuestions = Array.from(
    { length: 10 },
    (_, index) => `## Question ${index + 1}
By the Pigeonhole Principle, what is the minimum number of people in a group so that at least two of them share a birthday month, given $n = ${index + 12}$ and $\\gcd(48, 18)$ along the way?

- [ ] ${index + 11}
- [x] ${index + 13}
- [ ] ${index + 24}
`
  ).join("\n");
  const longFile = path.join(path.dirname(quizFile), "long-quiz.md");
  fs.writeFileSync(longFile, longQuestions);

  const quizName = `E2E Long Quiz ${Date.now()}`;
  const dialog = await openImportStep(quizName);
  await dialog
    .getByLabel("Drag the .md file here or click to choose")
    .setInputFiles(longFile);
  await expect(dialog.getByText("10 questions read")).toBeVisible();

  // The preview scrolls within its own short list, so a long quiz doesn't
  // stretch the dialog to the whole window: the step itself needs no scroll.
  const preview = dialog.getByRole("list");
  expect(
    await preview.evaluate((list) => list.scrollHeight > list.clientHeight)
  ).toBe(true);
  expect(
    await dialog
      .locator("form > div")
      .nth(1)
      .evaluate((step) => step.scrollHeight <= step.clientHeight + 1)
  ).toBe(true);

  const viewport =
    page.viewportSize() ??
    (await page.evaluate(() => ({
      height: window.innerHeight,
      width: window.innerWidth,
    })));
  const box = await dialog.boundingBox();
  expect(box).not.toBeNull();
  expect(box?.x ?? -1).toBeGreaterThanOrEqual(0);
  expect(box?.y ?? -1).toBeGreaterThanOrEqual(0);
  expect((box?.x ?? 0) + (box?.width ?? 0)).toBeLessThanOrEqual(viewport.width);
  expect((box?.y ?? 0) + (box?.height ?? 0)).toBeLessThanOrEqual(
    viewport.height
  );

  // Nothing inside sticks out sideways.
  expect(
    await dialog.evaluate(
      (element) => element.scrollWidth <= element.clientWidth
    )
  ).toBe(true);

  await expect(
    dialog.getByRole("button", { name: "Create quiz (10)" })
  ).toBeInViewport();
  await expect(dialog.getByRole("button", { name: "Back" })).toBeInViewport();
  await expect(dialog.getByRole("listitem").first()).toBeInViewport();

  // Take the whole quiz; the result screen must fit too: answers in a
  // scrolling left column, score and times on the right.
  await dialog.getByRole("button", { name: "Create quiz (10)" }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page
    .getByRole("row", { name: new RegExp(quizName) })
    .getByLabel("Take quiz")
    .click();
  const runner = page.getByRole("dialog", { name: quizName });

  async function answerRemaining(remaining: number): Promise<void> {
    if (remaining === 0) {
      return;
    }
    await runner.getByRole("radio").first().click();
    await runner
      .getByRole("button", {
        name: remaining === 1 ? "Finish quiz" : "Next question",
      })
      .click();
    await answerRemaining(remaining - 1);
  }
  await answerRemaining(10);

  const review = runner.getByRole("region", { name: "Answers" });
  const chart = runner.locator('[data-slot="chart"]');
  await expect(chart).toBeInViewport();
  await expect(
    runner.getByText("Total time", { exact: false })
  ).toBeInViewport();

  const resultBox = await runner.boundingBox();
  expect((resultBox?.y ?? 0) + (resultBox?.height ?? 0)).toBeLessThanOrEqual(
    viewport.height
  );
  expect(
    await runner.evaluate(
      (element) => element.scrollWidth <= element.clientWidth
    )
  ).toBe(true);

  const reviewBox = await review.boundingBox();
  const chartBox = await chart.boundingBox();
  expect(reviewBox?.x ?? 0).toBeLessThan(chartBox?.x ?? 0);

  // At most four answers are visible at once; the rest need a scroll. A
  // short window can show fewer, since the dialog must still fit in it.
  async function countVisibleAnswers(): Promise<number> {
    return await review.getByRole("list").evaluate((list) => {
      const listBox = list.getBoundingClientRect();
      return Array.from(list.children).filter((item) => {
        const itemBox = item.getBoundingClientRect();
        return (
          itemBox.top >= listBox.top - 1 && itemBox.bottom <= listBox.bottom + 1
        );
      }).length;
    });
  }
  expect(await countVisibleAnswers()).toBeLessThanOrEqual(4);

  // The list itself is cut right at the bottom of the fourth answer. Checked
  // on the list rather than by growing the window: macOS caps a window to its
  // screen, and a CI screen is too short for four of these long answers.
  const cutAtFourthAnswer = await review.getByRole("list").evaluate((list) => {
    const fourth = list.children[3] as HTMLElement;
    return (
      Number.parseFloat((list as HTMLElement).style.maxHeight) ===
      fourth.offsetTop + fourth.offsetHeight
    );
  });
  expect(cutAtFourthAnswer).toBe(true);

  // The last answer is reachable by scrolling the answers column.
  const lastAnswer = review.getByRole("listitem").last();
  await lastAnswer.scrollIntoViewIfNeeded();
  await expect(lastAnswer).toBeInViewport();
  await expect(chart).toBeInViewport();

  // A click outside by mistake keeps the quiz open and shakes it (the
  // shake is short, so it is recorded rather than caught in the act)...
  await runner.evaluate((runnerDialog) => {
    const recorder = window as unknown as ShakeRecorder;
    recorder.shakes = [];
    new MutationObserver(() =>
      recorder.shakes.push(runnerDialog.hasAttribute("data-shaking"))
    ).observe(runnerDialog, { attributeFilter: ["data-shaking"] });
  });
  await page.mouse.click(8, viewport.height - 8);
  const completeButton = runner.getByRole("button", { name: "Complete quiz" });
  await expect(completeButton).toBeInViewport();
  await expect
    .poll(() =>
      page.evaluate(() => (window as unknown as ShakeRecorder).shakes)
    )
    .toEqual([true, false]);

  // ...and "Complete quiz" moves on to rating it, like closing it does.
  await completeButton.click();
  await expect(completeButton).toBeHidden();
  // Rate it, or the pending rating reopens on the next launch.
  // An activity is rated on its own scale (docs/specs/rating-clarity.md).
  await page.getByRole("button", { name: "Didn't get it" }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
});
